### ISSUE TITLE
Package should import not depend on igraph and RBGL 

### ISSUE THREAD

**Issue by joeroe** [sebastien-plutniak/archeofrag#2]
Checking package installation as part of the JOSS review https://github.com/openjournals/joss-reviews/issues/4335.

`igraph` and `RBGL` are specified as `Depends` in `DESCRIPTION`, but this is generally recommended against (as explained here: https://r-pkgs.org/namespace.html#search-path).

Converting these to `Imports` and updating the code to use explicit namespaces (e.g. `igraph::graph_from_adjacency_matrix()`) would make the code more transparent and avoid unnecessarily loading all of `igraph` and `RBGL` (both big packages!) into the global namespace.

**Comment by zoometh** [comment]
Following the JOSS review https://github.com/openjournals/joss-reviews/issues/4335, confirming @joeroe note on [Depends _vs_ Imports](https://stackoverflow.com/questions/8637993/better-explanation-of-when-to-use-imports-depends#:~:text=Listing%20a%20package%20in%20either,%5B...%5D). Moving `igraph `and `RBGL `packages from `Depends `to `Imports` in the DESCRIPTION file, tagging each external function with its original package (ex: `igraph::is.igraph()`) will allow to understand which of `archaeofrag`'s functions are using the `RBGL `package

**Comment by sebastien-plutniak** [comment]
Thanks, all the functions imported from external packages (namely: grDevices, graphics, methods, utils, stats, igraph):
- are imported with `importFrom` in the `NAMESPACE` file, and
- are tagged in the .R files.
