### ISSUE TITLE
Is the RBGL dependency absolutely necessary?

### ISSUE THREAD

**Issue by joeroe** [sebastien-plutniak/archeofrag#3]
Checking package installation as part of the JOSS review https://github.com/openjournals/joss-reviews/issues/4335...

`RBGL` is not available on CRAN, only BioConductor. This is flagged in the README and the vignette, but I still think it's not ideal. It makes installation more difficult for new users and, I don't know about you, but in ten years of using R for archaeology I've never had to install a package from BioConductor! 

I'm not sure how many times functions from `RBGL` are used (#2 would help with that), but is it at all possible to e.g. substitute them for functions in a package available on CRAN, or copy the functions you need into `archaeofrag`? `RBGL` is licensed under https://opensource.org/licenses/Artistic-2.0 which I'm not familiar with though.

**Comment by sebastien-plutniak** [comment]
I agree, and I have made the suggested changes:

- the `igraph` package is now in the "imports" list: the archeofrag package use numerous functions from this package (n=41), justifying to conserve the dependency. All the `igraph` functions are individually imported in the `NAMESPACE` file with `importFrom`, improving transparency.
- the `RBGL` package is now in the "suggests" list: `RBGL` is an interface to the C++ BOOST library, and only one function is used by `archeofrag` (namely, `boyerMyrvoldPlanarityTest` to test planarity — it is, to my knowledge, the only R implementation of a planarity test algorithm). Consequently,  the installation of `RBGL` (and BioConductor) is now optional, and the functionalities based on this function have been rewritten and adapted to be conditional.
