### ISSUE TITLE
No unit tests

### ISSUE THREAD

**Issue by joeroe** [sebastien-plutniak/archeofrag#5]
Checking tests as part of the JOSS review https://github.com/openjournals/joss-reviews/issues/4335...

The package currently has basic automated tests from the examples in the .Rd files, run on GitHub actions.

You might consider more specific unit tests, especially if you intend to keep developing the package in a way that might break backwards compatibility. I've found [testthat](https://testthat.r-lib.org/) + [covr](https://covr.r-lib.org/) to be an effective framework for unit testing. See https://r-pkgs.org/tests.html for a guide.

**Comment by joeroe** [comment]
(Apologies, I somehow completely missed that you're already running R CMD check as a GitHub Action! Edited this accordingly – should be considered an absolutely 'optional' suggestions, not something blocking the JOSS submission.)

**Comment by sebastien-plutniak** [comment]
Thanks, yes I am considering adding unit tests in future developments of this package, in addition to the examples in .Rd files and the R CMD check GitHub Action.

**Comment by sebastien-plutniak** [comment]
@joeroe Finally, I have managed to add a series of unit tests and also used covr, as suggested.
